_target_: stopes.modules.speech.audio_zip.AudioZipModule
input_file: ???
output_dir: ???
output_prefix: ""
sample_rate: 16000
audio_format: ogg
# output the number of frames for each audio in manifest
store_num_frames: false
# output the entire input line in manifest (helpful for debugging)
store_input_line: false
# persist a file "/path/to/manifest.tsv.validated-ok" if successfull validation (helpful for debugging)
output_validation_token: false
# column should be index of the tsv file 0 or 2... or multiple indices at once separated by comma '0,6'
column: ???
nshards: ???

# If true, the audio paths will be sorted to speed up the audio reading (by taking advantage of
# memory cache when loading segments from the same file). This means the order of audios in the
# zip file is not the same as in the input TSV file. If False, no sorting is performed, the audios
# are appended to the zip file in the same order as in the input TSV file
sorted: true

# Whether to add duplicate segments to the zip file. Default true but this can be turned off
# for debugging purpose
no_duplicate: true