_target_: "stopes.modules.evaluation.generate_multi_bleu_detok_module.GenerateMultiBleuDetokModule"
src_lang: ???
tgt_lang: ???
checkpoint_dir: ??? # directory containing checkpoints
binarized_dir: ??? # contains binarized files for each lang and split
output_dir: ???
checkpoint_glob: "checkpoint[0-9]*.pt"  # pattern for file checkpoints in checkpoint_dir
beam: 5
batch_size: 32
batch_memory: 2 # mem_gb in Distributed requirements is = batch_memory * batch_size
splits:
  - valid
  - test
