name: lint_and_tests

on:
  # Trigger the workflow on push to master or any pull request
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        platform: [ubuntu-latest]
        python-version: [3.9]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install
        # Fairseq doesn't install with pip==22.1 we need to upgrade past it.
        # Also the version on pypi is from before Oct 2020.
        # wheel is required by fasttext to be installed correctly with recent pip versions
        # fairseq+omegaconf do not play nice when using pip > 24.1
        run: |
          python --version
          python -m pip install --upgrade 'pip>=22.1.2,<24.1'
          python -m pip show pip
          python -m pip install wheel
          python -m pip install 'git+https://github.com/facebookresearch/fairseq.git@v0.12.1'
          python -m pip install -e '.[dev,mono,mining,auto_pcp,speech,ust_common,local_prosody]'

      - name: isort
        run: isort --check --diff .
      - name: black
        run: black --check --diff .
      - name: pytest
        run: pytest
      - name: mypy
        run: 'mypy || echo "Warning: mypy still does not pass"'
